#include "utils/utils.hpp"
#include <iostream>
#include <vector>
#include "vector-operations/vector-operations.hpp"
#include <random>

int main() {
    /* std::vector<std::string> filenames = {"bit-arrays/a.txt","bit-arrays/e.txt","bit-arrays/i.txt","bit-arrays/o.txt","bit-arrays/u.txt"}; 
    std::vector<std::vector<std::vector<double>>> vec = read_files(filenames); 
    for(auto labeledV : vec) {
        //printVector(labeledV.at(0));
        printVector(labeledV.at(1));    
    }
    std::cout << "Number of training examples: " << vec.size() << "\n";
    */
    std::random_device rd;  // Will be used to obtain a seed for the random number engine
    std::mt19937 gen(rd()); // Standard mersenne_twister_engine seeded with rd()
    std::uniform_real_distribution<> dis(-1.0, 2.0);
    for (int n = 0; n < 10; ++n)
    {
        // Use dis to transform the random unsigned int generated by gen into a 
        // double in [1, 2). Each call to dis(gen) generates a new random double
        std::cout << dis(gen) << ' ';
    }
    std::cout << '\n';

    return 1;
}
